dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  geolocator: ^11.0.0
  flutter_spinkit: ^5.2.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.10
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300