class Cities {
  static const List<String> commonCities = [
    'London',
    'New York',
    'Tokyo',
    'Paris',

    'Singapore',
    'Hong Kong',
    'Shanghai',
    'Sydney',
    'Beijing',
    'Dubai',
    'Los Angeles',
    'Toronto',
    'San Francisco',
    'Chicago',
    'Mumbai',
    'Moscow',
    'São Paulo',
    'Seoul',
    'Berlin',
    'Madrid',
    'Mexico City',
    'Jakarta',
    'Amsterdam',
    'Brussels',

    'Bangkok',
    'Istanbul',
    'Rome',
    'Vienna',
    'Prague',
    'Budapest',
    'Warsaw',
    'Athens',
    'Cairo',
    'Cape Town',
    'Rio de Janeiro',
    'Buenos Aires',
    'Lima',
    'Santiago',
    'Vancouver',
    'Montreal',
    'Boston',
    'Miami',
    'Las Vegas',
    'Seattle',
    'Denver',
    'Dallas',
    'Houston',
    'Atlanta',
    'Philadelphia',
    'Washington DC',
    'San Diego',
    'Portland',
    'New Orleans',

    'Abidjan',
    'Accra',
    'Adana',
    'Addis Ababa',
    'Adelaide',
    'Agra',
    'Ahmadabad',
    'Aleppo',
    'Alexandria',
    'Algiers',
    'Almaty',
    'Amman',
    'Amritsar',
    'Ankara',
    'Anshan',
    'Baghdad',
    'Baku',
    'Bandung',
    'Bangalore',
    'Baotou',
    'Barcelona',
    'Barquisimeto',
    'Barranquilla',
    'Basrah',
    'Belem',
    'Belgrade',
    'Belo Horizonte',
    'Benghazi',
    'Benin City',
    'Bhopal',
    'Birmingham',
    'Bogota',
    'Brasilia',
    'Brazzaville',
    'Brisbane',
    'Bucharest',
    'Bursa',
    'Busan',
    'Cali',
    'Campinas',
    'Caracas',
    'Casablanca',
    'Changchun',
    'Changsha',
    'Changzhou',
    'Chelyabinsk',
    'Chengdu',
    'Chennai',
    'Chittagong',
    'Chongqing',
    'Ciudad Juarez',
    'Conakry',
    'Copenhagen',
    'Cordoba',
    'Curitiba',
    'Daegu',
    'Daejon',
    'Dakar',
    'Dalian',
    'Damascus',
    'Dar es Salaam',
    'Datong',
    'Delhi',
    'Dhaka',
    'Dnipropetrovsk',
    'Donetsk',
    'Douala',
    'Durban',
    'Ecatepec',
    'Ekaterinburg',
    'Faisalabad',
    'Fortaleza',
    'Foshan',
    'Freetown',
    'Fukuoka',
    'Fuzhou',
    'Giza',
    'Goiania',
    'Guadalajara',
    'Guangzhou',
    'Guarulhos',
    'Guatemala City',
    'Guayaquil',

    'Albuquerque',
    'Anaheim',
    'Anchorage',
    'Ann Arbor',
    'Arlington',
    'Asheville',
    'Aurora',
    'Austin',
    'Baltimore',
    'Boise',
    'Buffalo',
    'Charlotte',
    'Cincinnati',
    'Cleveland',
    'Colorado Springs',
    'Columbus',
    'Detroit',
    'El Paso',
    'Fresno',
    'Honolulu',
    'Indianapolis',
    'Jacksonville',
    'Kansas City',
    'Long Beach',
    'Louisville',
    'Memphis',
    'Milwaukee',
    'Minneapolis',
    'Nashville',
    'Oakland',
    'Oklahoma City',
    'Omaha',
    'Orlando',
    'Phoenix',
    'Pittsburgh',
    'Raleigh',
    'Sacramento',
    'Salt Lake City',
    'San Antonio',
    'San Jose',
    'St. Louis',
    'Tampa',
    'Tucson',
    'Tulsa',

    'Kuala Lumpur',
    'Manila',
    'Osaka',
    'Nagoya',
    'Yokohama',
    'Shenzhen',
    'Guangzhou',
    'Tianjin',
    'Chongqing',
    'Chengdu',
    'Nanjing',
    'Hangzhou',
    'Wuhan',
    'Xi\'an',
    'Suzhou',
    'Zhengzhou',
    'Qingdao',
    'Dongguan',
    'Foshan',
    'Harbin',
    'Jinan',
    'Dalian',
    'Changchun',
    'Kunming',
    'Taiyuan',
    'Shijiazhuang',
    'Nanchang',
    'Lanzhou',
    'Guiyang',
    'Haikou',
    'Urumqi',
    'Xining',
    'Lhasa',

    'Karachi',
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Gujranwala',
    'Multan',
    'Hyderabad',
    'Peshawar',
    'Quetta',
    'Islamabad',
    'Sargodha',
    'Sialkot',
    'Bahawalpur',
    'Jhang',
    'Sheikhupura',
    'Gujrat',
    'Sukkur',
    'Larkana',
    'Rahim Yar Khan',
    'Sahiwal',
    'Okara',
    'Dera Ghazi Khan',
    'Kasur',
    'Wah Cantonment',
    'Mardan',
    'Nawabshah',
    'Burewala',
    'Mingora',
    'Hafizabad',
    'Chiniot',
    'Jhelum',
    'Kamoke',
    'Khanewal',
    'Sadiqabad',
    'Turbat',
    'Mirpur Khas',
    'Muridke',
    'Khanpur',
    'Bahawalnagar',
    'Kohat',
    'Muzaffargarh',
    'Abbottabad',
    'Mandi Bahauddin',
    'Daska',
    'Pakpattan',
    'Dera Ismail Khan',
    'Jacobabad',
    'Chakwal',
    'Khuzdar',
    'Gojra',
    'Vehari',
    'Shikarpur',
    'Ahmedpur East',
    'Hub',
    'Chishtian',
    'Khairpur',
    'Dadu',
    'Samundri',
    'Ferozwala',
    'Attock',
    'Tando Adam',
    'Tando Allahyar',
    'Jaranwala',
    'Bolhari',
    'Muzaffarabad',
    'Hasilpur',
    'Kamalia',
    'Kot Abdul Malik',
    'Panjgur',
    'Arif Wala',
    'Gujranwala Cantonment',
    'Swabi',
    'Jampur',
    'Jatoi',
    'Wazirabad',
    'Layyah',
    'Shujabad',
    'Haroonabad',
    'Jalalpur Jattan',
    'Umerkot',
    'Lodhran',
    'Moro',
    'Kot Addu',
    'Mian Channu',
    'Khushab',
    'Rajanpur',
    'Mansehra',
    'Taxila',
    'Mirpur',
    'Kabal',
    'Bhakkar',
    'Narowal',
    'Chaman',
    'Mianwali',
    'Shakargarh',
    'Mailsi',
    'Nowshera',
    'Dipalpur',
    'Haveli Lakha',
    'Lala Musa',
    'Shahdadkot',
    'Charsadda',
    'Ghotki',
    'Sambrial',
    'Bhalwal',
    'Badin',
    'Taunsa Sharif',
    'Barikot',
    'Phool Nagar',
    'Tando Muhammad Khan',
    'Pattoki',
    'Shahdadpur',
    'Jauharabad',
    'Kamber Ali Khan',
    'Chichawatni',
    'Farooqabad',
    'Pishin',
    'Dera Murad Jamali',
    'Kotri',
    'Sangla Hill',
    'Gujar Khan',
    'Kharian',
    'Pasrur',
    'Shabqadar',
    'Kot Radha Kishan',
    'Ludhewala Waraich',
    'Renala Khurd',
    'Kandhkot',
    'Dera Allah Yar',
    ,
  ];
}
